// Recetario base para: esposo 43, esposa 40 (intolerante a la lactosa),
// hija 3 años (rechaza legumbres visibles).
//
// Todas las preparaciones están resueltas sin lactosa.
// leg: 'oculta'  -> lleva legumbre camuflada, apta para la hija
// leg: null      -> sin legumbre
// min            -> minutos totales de preparación
// Cantidades pensadas para 3 personas (a la hija sírvele cerca de un tercio del plato adulto).

export const RECETARIO = [
  /* ---------------------------- DESAYUNOS ---------------------------- */
  { id: 'd1', n: 'Avena con manzana rallada y canela', t: 'desayuno', min: 10, leg: null,
    ing: ['1 taza avena', '2 tazas bebida de almendras', '1 manzana', 'Canela', 'Miel'],
    pasos: ['Cocinar la avena con la bebida vegetal 5 min a fuego bajo.', 'Rallar la manzana e incorporar con canela.', 'Endulzar con un hilo de miel.'],
    truco: 'Deja la avena remojando de noche y en la mañana solo la calientas.' },
  { id: 'd2', n: 'Huevos revueltos con tomate y pan integral', t: 'desayuno', min: 10, leg: null,
    ing: ['4 huevos', '1 tomate', 'Pan integral', 'Aceite de oliva', 'Sal'],
    pasos: ['Saltear el tomate picado 2 min.', 'Agregar los huevos batidos y revolver a fuego bajo.', 'Servir sobre el pan tostado.'],
    truco: 'Fuego bajo y retirar antes de que cuaje del todo: quedan cremosos sin nada de crema.' },
  { id: 'd3', n: 'Panqueques de avena y plátano', t: 'desayuno', min: 15, leg: null,
    ing: ['2 plátanos maduros', '2 huevos', '1 taza avena', 'Canela'],
    pasos: ['Licuar todo hasta formar una mezcla espesa.', 'Cocinar porciones pequeñas en sartén antiadherente.', 'Voltear cuando burbujee la superficie.'],
    truco: 'La masa dura 2 días en el refrigerador. Para la hija, hazlos del tamaño de su palma.' },
  { id: 'd4', n: 'Tostadas con palta y huevo duro', t: 'desayuno', min: 12, leg: null,
    ing: ['3 huevos', '1 palta', 'Pan de molde integral', 'Limón', 'Sal'],
    pasos: ['Hervir los huevos 9 minutos.', 'Moler la palta con limón y sal.', 'Montar sobre el pan y coronar con huevo en rodajas.'],
    truco: 'Hierve 6 huevos de una vez: los que sobran sirven de colación.' },
  { id: 'd5', n: 'Yogur sin lactosa con fruta y granola', t: 'desayuno', min: 5, leg: null,
    ing: ['Yogur sin lactosa', 'Fruta de estación', 'Granola sin azúcar', 'Semillas de chía'],
    pasos: ['Servir el yogur en bowls.', 'Agregar fruta picada, granola y chía.'],
    truco: 'Arma los frascos la noche anterior y guarda la granola aparte para que no se ablande.' },
  { id: 'd6', n: 'Batido verde de plátano y espinaca', t: 'desayuno', min: 5, leg: null,
    ing: ['1 plátano', 'Puñado de espinaca', '1 taza bebida vegetal', '2 cdas avena', '1 cdta mantequilla de maní'],
    pasos: ['Licuar todo 1 minuto.', 'Servir de inmediato bien frío.'],
    truco: 'Con plátano congelado queda helado y la hija no percibe la espinaca.' },
  { id: 'd7', n: 'Tostadas francesas con bebida vegetal', t: 'desayuno', min: 12, leg: null,
    ing: ['6 rebanadas de pan', '3 huevos', '1/2 taza bebida de avena', 'Canela', 'Vainilla'],
    pasos: ['Batir huevos con la bebida vegetal, canela y vainilla.', 'Remojar el pan por ambos lados.', 'Dorar en sartén con poco aceite.'],
    truco: 'Usa pan del día anterior: absorbe mejor y no se deshace.' },
  { id: 'd8', n: 'Porridge de quinoa con frutos rojos', t: 'desayuno', min: 20, leg: null,
    ing: ['1 taza quinoa', '2 tazas bebida vegetal', 'Frutos rojos', 'Canela', 'Miel'],
    pasos: ['Lavar la quinoa y cocer con la bebida vegetal 15 min.', 'Agregar canela y fruta al servir.'],
    truco: 'Cocina el doble el domingo: se recalienta perfecto toda la semana.' },
  { id: 'd9', n: 'Panqueques dulces de lenteja roja', t: 'desayuno', min: 15, leg: 'oculta',
    ing: ['1 taza lenteja roja remojada', '2 huevos', '1 plátano', 'Canela', 'Vainilla'],
    pasos: ['Licuar la lenteja escurrida con huevos, plátano y vainilla.', 'Cocinar como panqueques en sartén caliente.', 'Servir con fruta.'],
    truco: 'La lenteja roja pierde el sabor terroso al licuarse con plátano. Es la puerta de entrada más fácil.' },
  { id: 'd10', n: 'Huevo pochado sobre tostada con queso maduro', t: 'desayuno', min: 12, leg: null,
    ing: ['3 huevos', 'Pan de masa madre', 'Queso parmesano o gouda maduro', 'Vinagre', 'Ciboulette'],
    pasos: ['Pochar los huevos en agua con un chorro de vinagre, 3 min.', 'Tostar el pan y rallar el queso encima.', 'Coronar con el huevo.'],
    truco: 'Los quesos madurados tienen muy poca lactosa y suelen tolerarse bien; parte con poca cantidad para confirmar.' },

  /* ---------------------------- COLACIONES ---------------------------- */
  { id: 'c1', n: 'Manzana en gajos con mantequilla de maní', t: 'colacion', min: 3, leg: null,
    ing: ['2 manzanas', 'Mantequilla de maní sin azúcar'],
    pasos: ['Cortar en gajos y servir con la mantequilla de maní para untar.'],
    truco: 'Un chorrito de limón evita que se oxide si va en la lonchera.' },
  { id: 'c2', n: 'Bastones de verdura con dip rosado', t: 'colacion', min: 10, leg: 'oculta',
    ing: ['1 taza garbanzos cocidos', '1 betarraga chica cocida', 'Jugo de limón', 'Aceite de oliva', 'Zanahoria y pepino'],
    pasos: ['Licuar garbanzos con betarraga, limón, aceite y sal hasta que quede liso.', 'Cortar las verduras en bastones y servir con el dip.'],
    truco: 'La betarraga tiñe el hummus de rosado fuerte. Preséntalo como salsa de princesa y desaparece el garbanzo.' },
  { id: 'c3', n: 'Mix de frutos secos y fruta deshidratada', t: 'colacion', min: 2, leg: null,
    ing: ['Almendras', 'Nueces', 'Pasas', 'Damascos deshidratados'],
    pasos: ['Mezclar y porcionar en bolsitas individuales.'],
    truco: 'Para la hija muele los frutos secos: enteros son riesgo de atoro a los 3 años.' },
  { id: 'c4', n: 'Galletas de avena y plátano', t: 'colacion', min: 20, leg: null,
    ing: ['2 plátanos maduros', '1 1/2 taza avena', 'Pasas', 'Canela'],
    pasos: ['Moler el plátano y mezclar con la avena, pasas y canela.', 'Formar montoncitos en la lata.', 'Hornear 15 min a 180°C.'],
    truco: 'Dos ingredientes base, cero azúcar añadida, rinden para tres colaciones.' },
  { id: 'c5', n: 'Brownie de porotos negros', t: 'colacion', min: 35, leg: 'oculta',
    ing: ['1 1/2 taza porotos negros cocidos', '2 huevos', '1/2 taza cacao', '1/3 taza miel', '1 cdta vainilla'],
    pasos: ['Licuar los porotos escurridos con huevos, cacao, miel y vainilla.', 'Verter en molde y hornear 25 min a 180°C.', 'Enfriar antes de cortar.'],
    truco: 'Enjuaga los porotos hasta que el agua salga clara: ahí se va todo el sabor a legumbre.' },
  { id: 'c6', n: 'Bolitas de dátil, avena y cacao', t: 'colacion', min: 15, leg: null,
    ing: ['1 taza dátiles sin carozo', '1 taza avena', '2 cdas cacao', 'Coco rallado'],
    pasos: ['Procesar dátiles con avena y cacao.', 'Formar bolitas y pasar por coco rallado.', 'Refrigerar 30 min.'],
    truco: 'Duran 10 días en frasco cerrado en el refrigerador.' },
  { id: 'c7', n: 'Fruta de estación con yogur sin lactosa', t: 'colacion', min: 5, leg: null,
    ing: ['Fruta de estación', 'Yogur sin lactosa', 'Semillas de maravilla'],
    pasos: ['Picar la fruta y mezclar con el yogur.', 'Espolvorear semillas.'],
    truco: 'Rota la fruta cada semana para no aburrir el paladar de la niña.' },
  { id: 'c8', n: 'Palomitas caseras con paprika', t: 'colacion', min: 8, leg: null,
    ing: ['1/2 taza maíz para cabritas', 'Aceite', 'Paprika', 'Sal'],
    pasos: ['Reventar el maíz en olla tapada con un poco de aceite.', 'Condimentar con paprika y sal.'],
    truco: 'Hechas en olla salen a un tercio del precio de las de microondas y sin aditivos.' },
  { id: 'c9', n: 'Huevo duro con tomate cherry', t: 'colacion', min: 10, leg: null,
    ing: ['3 huevos', 'Tomates cherry', 'Sal', 'Orégano'],
    pasos: ['Hervir los huevos 9 min y enfriar.', 'Servir con los cherry partidos y orégano.'],
    truco: 'Colación de alta saciedad para los adultos entre almuerzo y cena.' },
  { id: 'c10', n: 'Barritas horneadas de garbanzo y avena', t: 'colacion', min: 30, leg: 'oculta',
    ing: ['1 taza garbanzos cocidos', '1 taza avena', '1 plátano', 'Miel', 'Chips de cacao'],
    pasos: ['Procesar garbanzos con plátano y miel.', 'Mezclar con avena y chips, extender en molde.', 'Hornear 20 min a 180°C y cortar en barras.'],
    truco: 'Se congelan porcionadas: sacas una en la mañana y a la tarde está lista.' },

  /* ---------------------------- ALMUERZOS ---------------------------- */
  { id: 'a1', n: 'Espagueti con boloñesa de lenteja y carne', t: 'almuerzo', min: 35, leg: 'oculta',
    ing: ['250 g carne molida', '1 taza lentejas cocidas', 'Salsa de tomate', 'Cebolla', 'Zanahoria', 'Espagueti'],
    pasos: ['Licuar las lentejas con un poco de salsa hasta que no queden grumos.', 'Sofreír cebolla y zanahoria rallada, agregar la carne.', 'Incorporar el puré de lentejas y la salsa, cocer 15 min.', 'Servir sobre la pasta.'],
    truco: 'Mitad carne, mitad lenteja licuada: rinde el doble y la textura es idéntica a la boloñesa clásica.' },
  { id: 'a2', n: 'Albóndigas de pollo y garbanzo con puré', t: 'almuerzo', min: 40, leg: 'oculta',
    ing: ['400 g pollo molido', '1 taza garbanzos cocidos', '1 huevo', 'Papas', 'Bebida vegetal', 'Ajo'],
    pasos: ['Procesar los garbanzos hasta harina húmeda y mezclar con el pollo, huevo y ajo.', 'Formar albóndigas y hornear 20 min a 200°C.', 'Hacer puré de papas usando bebida vegetal en vez de leche.'],
    truco: 'El garbanzo reemplaza al pan rallado y suma proteína sin cambiar el sabor.' },
  { id: 'a3', n: 'Pollo al horno con papas y ensalada chilena', t: 'almuerzo', min: 50, leg: null,
    ing: ['Trutros de pollo', 'Papas', 'Tomate', 'Cebolla', 'Cilantro', 'Aceite de oliva'],
    pasos: ['Aliñar el pollo y hornear con las papas en rodajas, 40 min a 200°C.', 'Preparar la ensalada con la cebolla desflemada en agua fría.'],
    truco: 'Todo en una sola lata: menos loza y el jugo del pollo cocina las papas.' },
  { id: 'a4', n: 'Charquicán de zapallo y carne', t: 'almuerzo', min: 40, leg: null,
    ing: ['300 g carne molida', 'Zapallo', 'Papas', 'Choclo', 'Porotos verdes', 'Cebolla'],
    pasos: ['Sofreír cebolla y carne.', 'Agregar zapallo y papa en cubos con agua, cocer 25 min.', 'Moler grueso e incorporar choclo y porotos verdes.'],
    truco: 'Un huevo frito encima lo convierte en plato único.' },
  { id: 'a5', n: 'Arroz salteado con huevo y verduras', t: 'almuerzo', min: 20, leg: null,
    ing: ['3 tazas arroz cocido', '3 huevos', 'Zanahoria', 'Arvejas', 'Cebollín', 'Salsa de soya'],
    pasos: ['Saltear las verduras en sartén muy caliente.', 'Correr a un lado, cuajar los huevos y mezclar.', 'Agregar el arroz y la soya, saltear 3 min.'],
    truco: 'Arroz del día anterior, frío: es el secreto para que quede suelto.' },
  { id: 'a6', n: 'Tortilla de papa y zapallo italiano', t: 'almuerzo', min: 35, leg: null,
    ing: ['5 huevos', '3 papas', '1 zapallo italiano', 'Cebolla', 'Aceite de oliva'],
    pasos: ['Cocer las papas en láminas junto a la cebolla y el zapallo.', 'Mezclar con los huevos batidos.', 'Cuajar en sartén 6 min por lado.'],
    truco: 'Fría o caliente funciona igual: la del almuerzo sirve de cena.' },
  { id: 'a7', n: 'Crema de zapallo y garbanzo con crutones', t: 'almuerzo', min: 30, leg: 'oculta',
    ing: ['1/2 zapallo camote', '1 taza garbanzos cocidos', 'Cebolla', 'Caldo de verduras', 'Pan para crutones'],
    pasos: ['Cocer el zapallo con la cebolla en el caldo, 20 min.', 'Agregar los garbanzos y licuar hasta que quede sedoso.', 'Dorar cubos de pan al horno y servir encima.'],
    truco: 'El garbanzo licuado da la cremosidad que normalmente daría la crema de leche.' },
  { id: 'a8', n: 'Pastel de choclo simplificado', t: 'almuerzo', min: 50, leg: null,
    ing: ['400 g carne molida', 'Cebolla', '4 tazas choclo', 'Albahaca', 'Pollo cocido', 'Aceitunas'],
    pasos: ['Preparar el pino con cebolla y carne, condimentar con comino.', 'Licuar el choclo con albahaca y cocer hasta espesar.', 'Montar en fuente y gratinar 20 min.'],
    truco: 'Sin leche en la pasta de choclo: usa el agua del propio choclo y queda igual de cremosa.' },
  { id: 'a9', n: 'Nuggets de pollo y garbanzo al horno', t: 'almuerzo', min: 35, leg: 'oculta',
    ing: ['400 g pechuga de pollo', '3/4 taza garbanzos cocidos', '1 huevo', 'Avena molida', 'Paprika'],
    pasos: ['Procesar el pollo con los garbanzos y los condimentos.', 'Formar nuggets y pasar por avena molida.', 'Hornear 20 min a 200°C girando a la mitad.'],
    truco: 'Congela crudos separados: salen del congelador directo al horno.' },
  { id: 'a10', n: 'Fideos con salsa de tomate y atún', t: 'almuerzo', min: 20, leg: null,
    ing: ['Fideos', '2 latas de atún', 'Salsa de tomate', 'Ajo', 'Orégano', 'Aceitunas'],
    pasos: ['Sofreír el ajo, agregar la salsa y el orégano.', 'Incorporar el atún escurrido, cocer 5 min.', 'Mezclar con los fideos.'],
    truco: 'El plato de emergencia: 20 minutos con despensa básica.' },
  { id: 'a11', n: 'Hamburguesas de lenteja y carne', t: 'almuerzo', min: 30, leg: 'oculta',
    ing: ['250 g carne molida', '1 taza lentejas cocidas', '1 huevo', 'Avena', 'Pan de hamburguesa', 'Tomate y lechuga'],
    pasos: ['Moler las lentejas escurridas hasta pasta.', 'Mezclar con carne, huevo y avena, formar los medallones.', 'Dorar en sartén 4 min por lado.'],
    truco: 'Escurre bien la lenteja o la mezcla queda blanda y no toma forma.' },
  { id: 'a12', n: 'Pescado al horno con arroz y brócoli', t: 'almuerzo', min: 30, leg: null,
    ing: ['3 filetes de merluza o salmón', 'Limón', 'Arroz', 'Brócoli', 'Aceite de oliva'],
    pasos: ['Hornear el pescado con limón y aceite, 15 min a 200°C.', 'Cocer el arroz y el brócoli al vapor.'],
    truco: 'Al pescado de la hija sácale toda espina y córtalo en cubos: lo come mejor en trozos que en filete.' },
  { id: 'a13', n: 'Cazuela de pollo con zapallo y choclo', t: 'almuerzo', min: 45, leg: null,
    ing: ['Presas de pollo', 'Zapallo', 'Papas', 'Choclo', 'Zanahoria', 'Arroz'],
    pasos: ['Hervir el pollo con las verduras 30 min.', 'Agregar el arroz los últimos 15 min.', 'Servir con cilantro fresco.'],
    truco: 'Cocina una olla grande: la cazuela del domingo es la cena del lunes.' },
  { id: 'a14', n: 'Pizza casera con masa de garbanzo', t: 'almuerzo', min: 40, leg: 'oculta',
    ing: ['1 taza harina de garbanzo', '1 taza harina común', 'Levadura', 'Salsa de tomate', 'Queso sin lactosa', 'Orégano'],
    pasos: ['Amasar las harinas con levadura, agua tibia y sal. Reposar 20 min.', 'Estirar, cubrir con salsa y queso.', 'Hornear 12 min a 220°C.'],
    truco: 'Mitad harina de garbanzo es el máximo que no se nota ni en sabor ni en textura.' },
  { id: 'a15', n: 'Guiso de zapallo italiano con arroz', t: 'almuerzo', min: 30, leg: null,
    ing: ['3 zapallos italianos', 'Cebolla', 'Tomate', 'Arroz', 'Huevo', 'Comino'],
    pasos: ['Sofreír cebolla y tomate.', 'Agregar el zapallo en cubos, cocer 15 min.', 'Servir sobre arroz con huevo revuelto.'],
    truco: 'Guiso liviano y barato para media semana.' },

  /* ------------------------------- CENAS ------------------------------- */
  { id: 'n1', n: 'Sopa crema de brócoli y papa', t: 'cena', min: 25, leg: null,
    ing: ['1 brócoli', '2 papas', 'Cebolla', 'Caldo de verduras', 'Aceite de oliva'],
    pasos: ['Cocer todo en el caldo 20 min.', 'Licuar hasta que quede sedoso.', 'Ajustar sal y servir.'],
    truco: 'La papa aporta la cremosidad: no necesita nada de lácteo.' },
  { id: 'n2', n: 'Wrap de pollo con palta y lechuga', t: 'cena', min: 15, leg: null,
    ing: ['Tortillas de trigo', 'Pechuga de pollo cocida', 'Palta', 'Lechuga', 'Tomate', 'Limón'],
    pasos: ['Desmenuzar el pollo y mezclar con palta y limón.', 'Armar los wraps con lechuga y tomate.'],
    truco: 'Usa el pollo que sobró del almuerzo del día anterior.' },
  { id: 'n3', n: 'Revuelto de espinaca, huevo y papas', t: 'cena', min: 20, leg: null,
    ing: ['4 huevos', 'Espinaca', '2 papas', 'Cebolla', 'Aceite de oliva'],
    pasos: ['Dorar las papas en cubos con la cebolla.', 'Agregar la espinaca hasta que reduzca.', 'Incorporar los huevos y revolver.'],
    truco: 'La espinaca picada muy fina desaparece entre la papa.' },
  { id: 'n4', n: 'Ensalada tibia de quinoa, tomate y palta', t: 'cena', min: 25, leg: null,
    ing: ['1 taza quinoa', 'Tomate', 'Palta', 'Pepino', 'Limón', 'Aceite de oliva'],
    pasos: ['Lavar y cocer la quinoa 15 min.', 'Mezclar tibia con las verduras picadas.', 'Aliñar con limón y aceite.'],
    truco: 'Enjuaga la quinoa hasta que no haga espuma: así se le quita el amargor.' },
  { id: 'n5', n: 'Tortilla de acelga con pan', t: 'cena', min: 20, leg: null,
    ing: ['1 atado de acelga', '4 huevos', 'Cebolla', 'Ajo', 'Pan'],
    pasos: ['Cocer la acelga picada y escurrir bien.', 'Mezclar con huevo, cebolla y ajo.', 'Cuajar en sartén 5 min por lado.'],
    truco: 'Escurrir la acelga apretándola con las manos evita que la tortilla quede aguada.' },
  { id: 'n6', n: 'Croquetas de zapallo y lenteja al horno', t: 'cena', min: 35, leg: 'oculta',
    ing: ['2 tazas zapallo cocido', '1 taza lentejas cocidas', '1 huevo', 'Avena molida', 'Nuez moscada'],
    pasos: ['Moler el zapallo con las lentejas hasta pasta lisa.', 'Agregar huevo y avena hasta poder formar croquetas.', 'Hornear 20 min a 200°C.'],
    truco: 'El dulzor del zapallo tapa por completo la lenteja. Sírvelas con salsa de tomate para mojar.' },
  { id: 'n7', n: 'Sándwich caliente de pavo con sopa de verduras', t: 'cena', min: 20, leg: null,
    ing: ['Pan de molde', 'Pechuga de pavo', 'Tomate', 'Verduras surtidas', 'Caldo'],
    pasos: ['Hervir las verduras picadas en el caldo 15 min.', 'Armar y dorar los sándwiches en sartén.'],
    truco: 'Cena de viernes: rápida y sin loza.' },
  { id: 'n8', n: 'Budín de zapallo italiano con lenteja', t: 'cena', min: 40, leg: 'oculta',
    ing: ['3 zapallos italianos', '1 taza lentejas cocidas', '3 huevos', 'Cebolla', 'Avena'],
    pasos: ['Rallar el zapallo y escurrir el agua.', 'Licuar las lentejas y mezclar con huevos, zapallo y avena.', 'Hornear 30 min a 180°C.'],
    truco: 'Se corta en cuadros y sirve frío al día siguiente como colación.' },
  { id: 'n9', n: 'Puré mixto de papa y arveja con huevo a la copa', t: 'cena', min: 25, leg: 'oculta',
    ing: ['4 papas', '1 taza arvejas', '3 huevos', 'Bebida vegetal', 'Aceite de oliva'],
    pasos: ['Cocer papas y arvejas juntas 18 min.', 'Moler todo con bebida vegetal hasta puré verde claro.', 'Servir con huevo a la copa.'],
    truco: 'El color verde suave se vende como puré del bosque. La arveja es la legumbre más dulce y la mejor para empezar.' },
  { id: 'n10', n: 'Tacos de pollo con vegetales', t: 'cena', min: 25, leg: null,
    ing: ['Tortillas de maíz', 'Pechuga de pollo', 'Pimentón', 'Cebolla', 'Palta', 'Limón'],
    pasos: ['Saltear el pollo en tiras con pimentón y cebolla.', 'Calentar las tortillas.', 'Servir con palta y limón.'],
    truco: 'Deja que cada uno arme su taco: a los 3 años, poder elegir aumenta lo que come.' },
];
